name: Docker Image CI

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, ZK, Lightweight, Full]
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        ref: ${{ matrix.branch }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{ matrix.branch }}-$(date +%s)
